// <auto-generated />
// https://app.quicktype.io/

using System;
using System.Collections.Generic;

using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Neo.DebugAdapter
{
    public class DebugInfo
    {
        [JsonProperty("entrypoint")]
        public string Entrypoint { get; set; }

        [JsonProperty("methods")]
        public List<Method> Methods { get; set; }

        [JsonProperty("sequence-points")]
        public List<SequencePoint> SequencePoints { get; set; }

        public static DebugInfo FromJson(string json) =>
            JsonConvert.DeserializeObject<DebugInfo>(json, Neo.DebugAdapter.Converter.Settings);

        public string ToJson() =>
            JsonConvert.SerializeObject(this, Neo.DebugAdapter.Converter.Settings);
    }
}
