// <auto-generated />
// https://app.quicktype.io/

namespace Neo.DebugAdapter
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public class Method
    {
        [JsonProperty("namespace")]
        public string Namespace { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("display-name")]
        public string DisplayName { get; set; }

        [JsonProperty("start-address")]
        public int StartAddress { get; set; }

        [JsonProperty("end-address")]
        public int EndAddress { get; set; }

        [JsonProperty("parameters")]
        public List<Parameter> Parameters { get; set; }

        [JsonProperty("return-type")]
        public string ReturnType { get; set; }

        [JsonProperty("variables")]
        public List<object> Variables { get; set; }

        [JsonProperty("sequence-points")]
        public List<SequencePoint> SequencePoints { get; set; }
    }
}
