// <auto-generated />
// https://app.quicktype.io/

using System;
using System.Collections.Generic;

using System.Globalization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;

namespace Neo.DebugAdapter
{
    public class AbiInfo
    {
        [JsonProperty("hash")]
        public string Hash { get; set; }

        [JsonProperty("entrypoint")]
        public string Entrypoint { get; set; }

        [JsonProperty("functions")]
        public List<Function> Functions { get; set; }

        [JsonProperty("events")]
        public List<object> Events { get; set; }

        public static AbiInfo FromJson(string json) => 
            JsonConvert.DeserializeObject<AbiInfo>(json, Neo.DebugAdapter.Converter.Settings);

        public string ToJson() => 
            JsonConvert.SerializeObject(this, Neo.DebugAdapter.Converter.Settings);
    }
}
