// <auto-generated />
// https://app.quicktype.io/

namespace Neo.DebugAdapter
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public class SequencePoint
    {
        [JsonProperty("address")]
        public int Address { get; set; }

        [JsonProperty("document")]
        public string Document { get; set; }

        [JsonProperty("start-line")]
        public int StartLine { get; set; }

        [JsonProperty("start-column")]
        public int StartColumn { get; set; }

        [JsonProperty("end-line")]
        public int EndLine { get; set; }

        [JsonProperty("end-column")]
        public int EndColumn { get; set; }
    }
}
