variables:
  configuration: release

pool:
  vmImage: 'windows-2019'

trigger:
  batch: false
  branches:
    include:
    - master
    - release/*
  paths:
    include:
    - '*'
    exclude:
    - 'readme.md'
    - 'docs/*'

steps:

- task: UseDotNet@2
  displayName: 'use .NET Core SDK from global.json'
  inputs:
    packageType: 'sdk'
    useGlobalJson: true
    
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack neodebug library'
  inputs:
    command: 'pack'
    packagesToPack: './src/library/*.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)/library'
    includesymbols: true
    versioningScheme: 'off'

- task: PublishBuildArtifacts@1
  displayName: 'publish neodebug library nuget artifacts'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/library'
    artifactName: 'nuget-package'

- task: NuGetCommand@2
  displayName: 'NuGet push neodebug library to NeoDevPackages feed'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/library/*.nupkg;!$(Build.ArtifactStagingDirectory)/library/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '4b2bd186-f7a1-4f00-a22c-521ae5c47cd7/fc59ee4d-b5ed-4a8d-9520-240cd3712671'
    
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack neodebug adapter'
  inputs:
    command: 'pack'
    packagesToPack: './src/adapter/*.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)/adapter'
    includesymbols: true
    versioningScheme: 'off'

- task: PublishBuildArtifacts@1
  displayName: 'publish neodebug adapter nuget artifacts'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/adapter'
    artifactName: 'nuget-package'

- task: CopyFiles@2
  displayName: 'copy adapter nuget package into extension folder'
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)/adapter'
    Contents: 'Neo.Debug.Adapter.*.nupkg'
    TargetFolder: './src/extension'

- task: DeleteFiles@1
  displayName: 'remove symbol nuget packages from extension folder'
  inputs:
    sourceFolder:  './src/extension'
    contents: '*.symbols.nupkg'

- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: 'install'
    workingDir: './src/extension' 

- task: Npm@1
  displayName: 'npm run package'
  inputs:
    command: 'custom'
    customCommand: 'run package'
    workingDir: './src/extension' 

- task: CopyFiles@2
  displayName: 'copy VSIX package to Artifact Staging Directory'
  inputs:
    SourceFolder: './src/extension'
    Contents: '*.vsix'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/extension'

- task: PublishBuildArtifacts@1
  displayName: 'publish vsix build artifacts'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/extension'
    artifactName: 'VSIX-package'
